name: Firebase Deploy
on:
  push:
    branches:
    - master
jobs:
  main:
    name: Firebase Deploy Job
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Echo Hey
      run: echo Hey World!
    - name: Yarn install
      run: |
          sudo apt install yarn
          yarn
    - name: Deploy to Firebase Hosting
      uses: john-pickett/firebase-deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
